In [1]:
import pandas as pd
import numpy as np

import joblib

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

from sklearn.preprocessing import (

    OneHotEncoder,

    StandardScaler

)

pd.set_option("display.max_columns",None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv("cleaned_telco.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TenureGroup,MonthlyChargeCategory
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0-12 Months,Low
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0,25-48 Months,Medium
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,0-12 Months,Medium
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,25-48 Months,Low
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,0-12 Months,Medium

In [3]:
print(df.shape)

(7032, 23)

In [4]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'TenureGroup',
 'MonthlyChargeCategory']

In [5]:
df = df.drop(
    columns=["customerID"]
)

In [6]:
X = df.drop(
    "Churn",
    axis=1
)

y = df["Churn"]

In [7]:
numeric_features = [

    "tenure",

    "MonthlyCharges",

    "TotalCharges"

]

In [8]:
categorical_features = [

    col

    for col in X.columns

    if col not in numeric_features

]

categorical_features

['gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'TenureGroup',
 'MonthlyChargeCategory']

In [9]:
numeric_transformer = Pipeline(

    steps=[

        ("scaler",

         StandardScaler())

    ]

)

In [10]:
categorical_transformer = Pipeline(

    steps=[

        (

            "encoder",

            OneHotEncoder(

                handle_unknown="ignore"

            )

        )

    ]

)

In [11]:
preprocessor = ColumnTransformer(

    transformers=[

        (

            "num",

            numeric_transformer,

            numeric_features

        ),

        (

            "cat",

            categorical_transformer,

            categorical_features

        )

    ]

)

In [12]:
X_train,X_test,y_train,y_test = train_test_split(

    X,

    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)

In [13]:
print("Training :",X_train.shape)

print("Testing :",X_test.shape)

Training : (5625, 21)
Testing : (1407, 21)

In [14]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['tenure', 'MonthlyCharges', 'TotalCharges']),
                                ('cat',
                                 Pipeline(steps=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'SeniorCitizen', 'Partner',
                                  'Dependents', 'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod',
                                  'TenureGroup', 'MonthlyChargeCategory'])])

In [15]:
X_train_processed = preprocessor.transform(

    X_train

)

X_test_processed = preprocessor.transform(

    X_test
)

In [16]:
print(

    X_train_processed.shape

)

print(

    X_test_processed.shape

)

(5625, 54)
(1407, 54)

In [17]:
feature_names = preprocessor.get_feature_names_out()

feature_names

array(['num__tenure', 'num__MonthlyCharges', 'num__TotalCharges',
       'cat__gender_Female', 'cat__gender_Male', 'cat__SeniorCitizen_0',
       'cat__SeniorCitizen_1', 'cat__Partner_No', 'cat__Partner_Yes',
       'cat__Dependents_No', 'cat__Dependents_Yes',
       'cat__PhoneService_No', 'cat__PhoneService_Yes',
       'cat__MultipleLines_No', 'cat__MultipleLines_No phone service',
       'cat__MultipleLines_Yes', 'cat__InternetService_DSL',
       'cat__InternetService_Fiber optic', 'cat__InternetService_No',
       'cat__OnlineSecurity_No',
       'cat__OnlineSecurity_No internet service',
       'cat__OnlineSecurity_Yes', 'cat__OnlineBackup_No',
       'cat__OnlineBackup_No internet service', 'cat__OnlineBackup_Yes',
       'cat__DeviceProtection_No',
       'cat__DeviceProtection_No internet service',
       'cat__DeviceProtection_Yes', 'cat__TechSupport_No',
       'cat__TechSupport_No internet service', 'cat__TechSupport_Yes',
       'cat__StreamingTV_No', 'cat__StreamingTV_No internet service',
       'cat__StreamingTV_Yes', 'cat__StreamingMovies_No',
       'cat__StreamingMovies_No internet service',
       'cat__StreamingMovies_Yes', 'cat__Contract_Month-to-month',
       'cat__Contract_One year', 'cat__Contract_Two year',
       'cat__PaperlessBilling_No', 'cat__PaperlessBilling_Yes',
       'cat__PaymentMethod_Bank transfer (automatic)',
       'cat__PaymentMethod_Credit card (automatic)',
       'cat__PaymentMethod_Electronic check',
       'cat__PaymentMethod_Mailed check', 'cat__TenureGroup_0-12 Months',
       'cat__TenureGroup_13-24 Months', 'cat__TenureGroup_25-48 Months',
       'cat__TenureGroup_49-60 Months', 'cat__TenureGroup_61-72 Months',
       'cat__MonthlyChargeCategory_High',
       'cat__MonthlyChargeCategory_Low',
       'cat__MonthlyChargeCategory_Medium'], dtype=object)

In [18]:
X_train_processed = pd.DataFrame(

    X_train_processed,

    columns=feature_names

)

X_test_processed = pd.DataFrame(

    X_test_processed,

    columns=feature_names

)

In [19]:
X_train_processed.head()

,num__tenure,num__MonthlyCharges,num__TotalCharges,cat__gender_Female,cat__gender_Male,cat__SeniorCitizen_0,cat__SeniorCitizen_1,cat__Partner_No,cat__Partner_Yes,cat__Dependents_No,cat__Dependents_Yes,cat__PhoneService_No,cat__PhoneService_Yes,cat__MultipleLines_No,cat__MultipleLines_No phone service,cat__MultipleLines_Yes,cat__InternetService_DSL,cat__InternetService_Fiber optic,cat__InternetService_No,cat__OnlineSecurity_No,cat__OnlineSecurity_No internet service,cat__OnlineSecurity_Yes,cat__OnlineBackup_No,cat__OnlineBackup_No internet service,cat__OnlineBackup_Yes,cat__DeviceProtection_No,cat__DeviceProtection_No internet service,cat__DeviceProtection_Yes,cat__TechSupport_No,cat__TechSupport_No internet service,cat__TechSupport_Yes,cat__StreamingTV_No,cat__StreamingTV_No internet service,cat__StreamingTV_Yes,cat__StreamingMovies_No,cat__StreamingMovies_No internet service,cat__StreamingMovies_Yes,cat__Contract_Month-to-month,cat__Contract_One year,cat__Contract_Two year,cat__PaperlessBilling_No,cat__PaperlessBilling_Yes,cat__PaymentMethod_Bank transfer (automatic),cat__PaymentMethod_Credit card (automatic),cat__PaymentMethod_Electronic check,cat__PaymentMethod_Mailed check,cat__TenureGroup_0-12 Months,cat__TenureGroup_13-24 Months,cat__TenureGroup_25-48 Months,cat__TenureGroup_49-60 Months,cat__TenureGroup_61-72 Months,cat__MonthlyChargeCategory_High,cat__MonthlyChargeCategory_Low,cat__MonthlyChargeCategory_Medium
0,1.321816,0.981556,1.659900,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,-0.267410,-0.971546,-0.562252,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,1.444064,0.837066,1.756104,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,-1.204646,0.641092,-0.908326,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.669826,-0.808787,-0.101561,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [20]:
joblib.dump(

    preprocessor,

    "preprocessing_pipeline.pkl"

)

print("Pipeline Saved Successfully")

Pipeline Saved Successfully

In [21]:
X_train_processed.to_csv(

    "X_train.csv",

    index=False

)

X_test_processed.to_csv(

    "X_test.csv",

    index=False

)

y_train.to_csv(

    "y_train.csv",

    index=False

)

y_test.to_csv(

    "y_test.csv",

    index=False

)

In [22]:
summary = pd.DataFrame({

    "Category":[

        "Original Features",

        "Numerical Features",

        "Categorical Features",

        "Encoded Features",

        "Training Samples",

        "Testing Samples"

    ],

    "Count":[

        len(df.columns)-1,

        len(numeric_features),

        len(categorical_features),

        X_train_processed.shape[1],

        X_train.shape[0],

        X_test.shape[0]

    ]

})

summary

               Category  Count
0     Original Features     21
1    Numerical Features      3
2  Categorical Features     18
3      Encoded Features     54
4      Training Samples   5625
5       Testing Samples   1407

In [23]:
print("="*70)

print("FEATURE ENGINEERING COMPLETED")

print("="*70)

print()

print("✔ Data Split Successfully")

print("✔ One-Hot Encoding Applied")

print("✔ Numerical Features Scaled")

print("✔ Data Leakage Prevented")

print("✔ Preprocessing Pipeline Saved")

print("✔ Training/Test Data Saved")

======================================================================
FEATURE ENGINEERING COMPLETED
======================================================================

✔ Data Split Successfully
✔ One-Hot Encoding Applied
✔ Numerical Features Scaled
✔ Data Leakage Prevented
✔ Preprocessing Pipeline Saved
✔ Training/Test Data Saved